config/routes.rb
Rails.application.routes.draw do

  root 'homes#top'
  get 'homes/about'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:show, :edit, :update]
  resources :posts do
  	 resources :post_comments, only: [:create, :destroy]
  	 resource :favorites, only: [:create, :destroy]
  	 resources :maps, only: [:show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	attachment :image
	
	has_many :post_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
	belongs_to :user
	belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image

  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_search

  def after_sign_in_path_for(resource)
      posts_path
  end

  def after_sign_out_path_for(resource)
      root_path
  end

  def set_search
      @search = Post.ransack(params[:q])
      @search_posts = @search.result.page(params[:page])
  end

  protected
  
  def configure_permitted_parameters
  	  devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	def create
		@favorite = current_user.favorites.new(post_id: params[:post_id])
		@favorite.save
		redirect_back(fallback_location: root_path)
	end

	def destroy
		@favorite = current_user.favorites.find_by(post_id: params[:post_id])
		@favorite.destroy
		redirect_back(fallback_location: root_path)
	end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

	def top
	end
	
	def about
	end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
	def create
		@post = Post.find(params[:post_id])
		@comment = PostComment.new(post_comment_params)
		@comment.user_id = current_user.id
		@comment.post_id = @post.id
		@comment.save
		redirect_to post_path(@post.id)
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.post_comments.find(params[:id])
		@comment.destroy
		redirect_to post_path(@post.id)
	end

	private
	def post_comment_params
		params.require(:post_comment).permit(:comment)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	  before_action :authenticate_user!
	  before_action :correct_user, only: [:edit, :update, :destroy]
	def new
	  @post = Post.new
	  @user = current_user
	end

	def index
	  @posts = Post.page(params[:page]).reverse_order
	  @user = current_user
	  @all_ranks = Post.find(Favorite.group(:post_id).order(Arel.sql('count(post_id) desc')).limit(3).pluck(:post_id))
	  #order/pluckの引数にSQL文字列を渡すと警告がでる→DEPRECATION WARNING
	  #コンソールの警告の文末の通り、SQL文字列.orderの後にArel.sql()で対策
	end

	def show
	  @post = Post.find(params[:id])
	  @user = @post.user
	  @post_comment = PostComment.new
	end

	def edit
	  @post = Post.find(params[:id])
	end

	def create
	  @post = Post.new(post_params)
	  @post.user_id = current_user.id
	  @post.save
	  redirect_to posts_path
    end

    def update
      @post = Post.find(params[:id])
      @post.update(post_params)
      redirect_to post_path
    end

    def destroy
      @post = Post.find(params[:id])
      @post.destroy
      redirect_to posts_path
    end

    private
    def post_params
        params.require(:post).permit(:title, :subtitle, :region, :area, :body,
        	:image)
    end

    def correct_user
    	post = Post.find(params[:id])
    	userid = post.user
    	if current_user!= userid
    	   redirect_to post_path
    	end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	  before_action :authenticate_user!
	  before_action :correct_user, only: [:edit, :update]
	def show
		@user = User.find(params[:id])
		@post = Post.new
		@posts = @user.posts.page(params[:page]).reverse_order
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		@user.update(user_params)
		redirect_to user_path
	end

	private
	def user_params
		params.require(:user).permit(:name, :introduction, :profile_image)
	end

	def correct_user
		user = User.find(params[:id])
		if current_user!= user
		   redirect_to user_path
		end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/about.html.erb
<body>
  <div class="container">
	  <div class="row">
	  	  <div class="col-xs-3"></div>
	  	  <div class="col-xs-6">
			  <h3><span><about class="about_title">〜地域の魅力をもっと多くの人に〜</span></h3>

              <table class="about_field">
              	  <tr>
				  	  <td>
				  	  	 <p>このサイトでは、旅行して楽しかった場所や<br>
					     住んでいる地域・その周辺の良いと感じた場所を<br>
					     投稿・閲覧できる地域情報サイトです。</p>
					  </td>
				  </tr>

                  <tr>
                  	  <td>
					     <p>＜利用における説明＞</p>
					     <p>初めてのご利用の方には「新規会員登録」をお願いしております。<br>
					     ※以前「新規会員登録」をしてご利用頂いた方には、「ログイン」ページより必要事項を入力後、投稿一覧画面にアクセス頂けます。</p>
					  </td>
				  </tr>

                  <tr>
					  <td>
					  	 <p>１. 投稿一覧<br>
						 投稿一覧画面より、全ての投稿を閲覧することが出来ます。</p>

						 <p>２. マイページ<br>
						 マイページ画面より、プロフィールの作成を行うことが出来ます。<br>
						 また、ご自身が投稿した内容も全て確認する事が可能です。</p>

						 <p>３. 投稿について<br>
						 「投稿一覧画面」及び「マイページ画面」のどちらからでもサイドバーにあるリンクより、画像を含めて投稿を行うことが出来ます。</p>
                      </td>
				  </tr>

                  <tr>
                      <td>
                      	 <p>＜その他機能について＞</p>
						 <p>１. いいね機能<br>
						 いいなと思った投稿に、１人１つ「いいね」をつけることが出来ます。</p>

						 <p>２. コメント機能<br>
						 投稿詳細画面より、投稿に対する意見や感想などコメントを入力することが出来ます。</p>

						 <p>３. 検索機能<br>
						 ヘッダーにある検索欄より、閲覧したい「都道府県名」を入力して頂くことで、投稿内容を絞って閲覧する事が出来ます。</p>

						 <p>４. Google・MAP機能<br>
						 投稿詳細画面より、Google・MAPを用いた場所や地域などの検索を行う事が出来ます。</p>
					  </td>
                  </tr>
			  </table>

			  <div class="btn-wrapper">
			  	  <%= link_to '新規会員登録', new_user_registration_path, class: "btn btn-success btn-block" %>
				  <%= link_to 'ログイン', new_user_session_path, class: "btn btn-primary btn-block" %>
				  <%= link_to 'HOMEに戻る', root_path, class: "btn btn-info btn-block" %>
			  </div>
	      </div>
	  </div>
  </div>
</body>

app/views/homes/top.html.erb
<body>
  <div class="container">
	  <div class="row">
	  	  <div class="col-xs-3"></div>
	  	  <div class="col-xs-6">
			    <br>ようこそ、ブレイクZONEへ！！
				<br>このサイトでは、旅行して楽しかった場所や
				<br>住んでいる地域・その周辺の良いと感じた場所を
				<br>投稿・閲覧できる地域情報サイトです。
				<br><%= link_to "詳しくはこちら＝＞", homes_about_path %><br>

			  <div id="container">
				  <div id="theTarget">
					  <div class="image1"></div>
					  <div class="image2"></div>
					  <div class="image3"></div>
					  <div class="image4"></div>
				  </div>
			  </div>

			  <div class="btn-wrapper">
			  	 <br><%= link_to '新規会員登録', new_user_registration_path, class: "btn btn-success btn-block" %>
				  <%= link_to 'ログイン', new_user_session_path, class: "btn btn-primary btn-block" %>
			  </div>
	      </div>
	  </div>
  </div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ブレイクZONE</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="body-wrap">
    <div class="row">
      <div class="header">
        <div class="text-center">
          <h1 class="title">ブレイクZONE</h1>
        </div>

        <nav class="navbar navbar-default">
          <div class="col-xs-5 col-xs-offset-4">
            <ul class="nav navbar-nav">
              <% if user_signed_in? %>
                <li> <%= link_to "投稿一覧", posts_path %> </li>
                <li> <%= link_to "マイページ", user_path(current_user) %> </li>
                <li> <%= link_to "ログアウト", destroy_user_session_path,method: :delete %> </li>
                <li><%= search_form_for @search, url: posts_path do |f| %>
                      <%= f.text_field :region_cont, placeholder: '気になる都道府県名を入力', :size => "30*30" %>
                      <%= f.submit ("検索する") %></li>
                    <% end %>
              <% else %>
                <li> <%= link_to "HOME", root_path %> </li>
                <li> <%= link_to "ブレイクZONEについて", homes_about_path %> </li>
                <li> <%= link_to "ログイン", new_user_session_path %> </li>
                <li> <%= link_to "新規会員登録", new_user_registration_path %> </li>
              <% end %>
            </ul>
          </div>
        </nav>
      </div>

      <%= yield %>
      <div class="footer">
        ©ALL right recerved by Takumi Shibata
      </div>
    </div>
  </body>
</html>

app/views/posts/edit.html.erb
<div class="container">
  <div class="row">
  	  <h3>編集内容を入力してください</h3>

  	  <div class="col-md-3"></div>
  	  <div class="col-md-5">
  	  	  <%= form_for(@post) do |f| %>
  	  	      <div class="edit-field">
			      <table class="edit-table">
			      	  <tr>
			      	  	 <th><%= f.label :タイトル %></th>
			      	  	 <td><%= f.text_field :title %></td>
			      	  </tr>

			      	  <tr>
			      	  	 <th><%= f.label :サブタイトル %></th>
			      	  	 <td><%= f.text_field :subtitle %></td>
			      	  </tr>

			      	  <tr>
			      	  	 <th><%= f.label :都道府県名 %></th>
			      	  	 <td><%= f.text_field :region %></td>
			      	  </tr>

			      	  <tr>
			      	  	 <th><%= f.label :市区町村・エリア名 %></th>
			      	  	 <td><%= f.text_field :area %></td>
			      	  </tr>

			      	  <tr>
			      	  	 <th><%= f.label :本文 %></th>
			      	  	 <td><%= f.text_area :body %></td>
			      	  </tr>

			      	  <tr>
			      	  	 <th><%= f.label :画像 %></th>
			      	  	 <td><%= f.attachment_field :image %></td>
			      	  </tr>
			      </table>
			  </div>

			  <div class="actions">
			  	 <button class="btn btn-primary btn-block" type="submit">更新する</button>
			  </div>
	      <% end %>

          <div class="col-md-3"></div>
	      <div class="col-md-7">
		      <%= link_to "詳細画面に戻る", post_path(@post.id) %>
			  <span> | </span>
			  <%= link_to "一覧画面に戻る", posts_path %>
		  </div>
	  </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container">
  <div class="row">

     <!--サイドバー-->
  	 <div class="side-bar col-xs-4">
  	 	  <div class="new_field">
  	          <h2>新規投稿</h2>
              <%= link_to "新しい投稿はこちらから＝＞", new_post_path %>
          </div>
          
          <!--いいねランキング-->
          <div class="favorite_ranks">
          	  <h2>いいね数ランキング</h2>
          </div>

          <% @all_ranks.each.with_index(1) do |post, i| %>
          	  <table class="table table-striped">
          	  	  <tr>
          	         <h4>第<%= i %>位</h4>
          	      </tr>

          	      <tr>
          	         <th>投稿者：<%= post.user.name %>さん</th>
          	      </tr>

          	      <tr>
          	         <th>タイトル：<%= post.title %></th>
          	      </tr>

          	      <tr>
          	         <th><span class="glyphicon glyphicon-heart" aria-hidden="true" style="color: red;"></span> <%= post.favorites.count %>いいね！<%= link_to "詳しくはこちら＝＞", post_path(post.id) %></th>
          	      </tr>
          	  </table>
          <% end %>
     </div>

     <!--投稿一覧-->
     <div class="main col-xs-8">
          <div class="list">
	          <h2>投稿一覧<h2>
	      </div>

		  <% @search_posts.each do |post| %>
		      <table class="table table-striped">
		          <tr>
			          <td><%= attachment_image_tag post, :image,size: '100x100', fallback: "no_image.jpg"  %></td>
			          <th class="col-xs-8">
			              タイトル　　　　　　<%= post.title %><br>
			              サブタイトル　　　　<%= post.subtitle %><br>
			              都道府県名　　　　　<%= post.region %><br>
			              市区町村・エリア名　<%= post.area %><br>
			          </th>

                      <!--いいね数＋コメント数表示-->
			          <th class="col-xs-4">
			              <% if post.favorited_by?(current_user) %>
							  <%= link_to post_favorites_path(post.id), method: :delete do %>
							  <span class="glyphicon glyphicon-heart" aria-hidden="true" style="color: red;"></span>
							  <%= post.favorites.count %>いいね<br>
							  <% end %>
						  <% else %>
							  <%= link_to post_favorites_path(post.id), method: :post do %>
							  <span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span>
							  <%= post.favorites.count %>いいね<br>
							  <% end %>
						  <% end %>
			              コメント数：<%= post.post_comments.count %><br>
			              投稿者：<%= post.user.name %>さん<br>
			              <%= link_to "詳しくはこちら＝＞", post_path(post.id) %>
			          </th>
			      </tr>
		      </table>
		  <% end %>
		  <!--ページネーション-->
		  <%= paginate @posts, class: "paginate" %>
	 </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <div class="row">
      <h3>投稿内容を入力してください<h3>
      	
      <div class="col-md-2"></div>
	  <div class="col-md-8">
	      <%= form_for(@post) do |f| %>

	         <div class="new-field">
		         <table class="new-table">
			           <tr>
			           	 <th><%= f.label :タイトル %></th>
			           	 <td><%= f.text_field :title %></td>
			           </tr>

			      	   <tr>
			      	   	 <th><%= f.label :サブタイトル %></th>
			      	   	 <td><%= f.text_field :subtitle %></td>
			      	   </tr>

			      	   <tr>
			      	   	 <th><%= f.label :都道府県名 %></th>
			      	   	 <td><%= f.text_field :region %></td>
			      	   </tr>

			      	   <tr>
			      	   	 <th><%= f.label :市区町村・エリア名 %></th>
			      	   	 <td><%= f.text_field :area %></td>
			      	   </tr>

			      	   <tr>
			      	   	 <th><%= f.label :本文 %></th>
			      	   	 <td><%= f.text_area :body %></td>
			      	   </th>

			      	   <tr>
			      	 	 <th><%= f.label :画像 %></th>
			      	 	 <td><%= f.attachment_field :image %></td>
			      	   </tr>
		         </table>
		      </div>

	         <div class="actions">
	              <button class="btn btn-primary btn-block" type="submit">投稿する</button>
	         </div>
	      <% end %>

	      <div class="col-md-3"></div>
	      <div class="col-md-7">
		      <%= link_to "一覧画面に戻る", posts_path %>
			  <span> | </span>
			  <%= link_to "マイページに戻る", user_path(@user.id) %>
		  </div>
	 </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-2"></div>
		<div class="col-xs-8">

		  <table class="table table-striped">
		  	  <tr>
				  <td class="col-xs-3">タイトル</td>
				  <th><%= @post.title %></th>
			  </tr>

			  <tr>
				  <td>サブタイトル</td>
				  <th><%= @post.subtitle %></th>
			  </tr>

			  <tr>
				  <td>都道府県名</td>
				  <th><%= @post.region %></th>
			  </tr>
			  
			  <tr>
				  <td>市区町村・エリア名</td>
				  <th><%= @post.area %></th>
			  </tr>
		  </table>

          <table class="table table-striped">
			  <tr>
				  <td><%= attachment_image_tag @post, :image,size: '300x300', fallback: "no_image.jpg"  %></td>
				  <!--Google・MAP機能-->
				  <td>
				  	  <input id="address" type="textbox" value="">
				      <input type="button" value="検索する" onclick="codeAddress()">
				      <div id='map'></div>
				  </td>
		      </tr>
		  </table>
                    <!--Google・MAP機能-->
					<style>
					#map{
					  height: 275px;
					  width: 400px;

					}
					</style>

					<script>
					let map
			        let geocoder
					function initMap(){
						geocoder = new google.maps.Geocoder()

					    map = new google.maps.Map(document.getElementById('map'), {
						center: {lat: -34.397, lng: 150.644},
						zoom: 8
						});
					}
					function codeAddress(){
					  let inputAddress = document.getElementById('address').value;

					  geocoder.geocode( { 'address': inputAddress}, function(results, status) {
					    if (status == 'OK') {
					      map.setCenter(results[0].geometry.location);

					      var marker = new google.maps.Marker({
					          map: map,
					          position: results[0].geometry.location
					      });
					    } else {
					      alert('Geocode was not successful for the following reason: ' + status);
					    }
					  });
					}
					</script>

					<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAcIyvTMta5XydDaSkV0AyK65hrMPPj-oE&callback=initMap" async defer></script>

		  <table class="table table-striped">
		  	  <tr>
			      <th><%= @post.body %></th>
			  </tr>
		  </table>

          <!--いいね数＋コメント数表示-->
		  <table class="list">
		  	  <tr>
				  <% if @post.favorited_by?(current_user) %>
					  <th><%= link_to post_favorites_path(@post), method: :delete do %>
					  <span class="glyphicon glyphicon-heart" aria-hidden="true" style="color: red;"></span>
					  <%= @post.favorites.count %>いいね</th>
					  <% end %>
				  <% else %>
					  <th><%= link_to post_favorites_path(@post), method: :post do %><span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span>
					  <%= @post.favorites.count %>いいね</th>
					  <% end %>
				  <% end %>
					<th class="col-xs-4">コメント数：<%= @post.post_comments.count %></th>
					<td class="col-xs-1"><%= link_to "一覧画面に戻る", posts_path, class: "btn btn-primary btn-sm" %></td>
					<td class="col-xs-1"><%= link_to "投稿を編集する", edit_post_path, class: "btn btn-success btn-sm" %></td>
					<td class="col-xs-1"><%= link_to "投稿を削除する", post_path, method: :delete,data: {confirm: "本当に投稿を削除しますか？"},class: "btn btn-danger btn-sm" %></td>
			  </tr>
		  </table>

          <!--投稿したユーザ情報-->
		  <table class="user-info table table-striped">
		  	  <tr>
				  <td><%= attachment_image_tag @user, :profile_image, size: '80x80', fallback: "no_image.jpg" %></td>
				  <th class="col-xs-12">
				  	  投稿者：<%= @user.name %><br>
                      自己紹介文：<%= @user.introduction %><br>
                      <%= link_to "この方の投稿をもっと閲覧する＝＞", user_path(@user.id), class: "btn btn-primary btn-sm" %>
                  </th>
			  </tr>
		  </table>

          <!--コメントフォーム-->
		  <%= form_for [@post, @post_comment] do |f| %>
		      <%= f.text_area :comment, rows:'4', class: "form-control",placeholder: "コメントをここに入力" %>
		      <%= f.submit "送信する", class: "btn btn-default pull-right" %>
		  <% end %>

          <!--コメント表示-->
		  <% @post.post_comments.each do |post_comment| %>
		      <table class="table table-striped">
		      	  <tr>
		             <td class="col-xs-3"><%= post_comment.user.name %></td>
		             <td class="col-xs-3"><%= post_comment.created_at.strftime('%Y/%m/%d') %></td>
		             <th class="col-xs-3"><%= post_comment.comment %></th>
		             <td class="col-xs-3"><%= link_to "コメントを削除する", post_post_comment_path(@post, post_comment.id), method: :delete,data: {confirm: "本当に投稿を削除しますか？"},class: "btn btn-danger btn-sm" %></td>
		          </tr>
		      </table>
		  <% end %>
	  </div>
	</div>
</div>

app/views/users/edit.html.erb
<div class="container">
	<div class="row">
		<h3>編集内容を入力してください</h3>

		<div class="col-xs-3"></div>
		<div class="col-xs-6">
			<%= form_for(@user) do |f| %>
			  <div class="edit-field">
			  	 <table class="edit-table">
			  	   <tr>
			  	 	 <th><%= f.label :名前（ニックネーム可）%></th>
			  	 	 <td><%= f.text_field :name %></td>
			  	   </tr>

                   <tr>
			  	 	 <th><%= f.label :自己紹介文 %></th>
			  	 	 <td><%= f.text_field :introduction, :size => "50*50" %></td>
			  	   </tr>

			  	   <tr>
			  	   	 <th><%= f.label :画像 %></th>
			  	   	 <td><%= f.attachment_field :profile_image %></td>
			  	   </tr>
			  	 </table>
			  </div>

			  <div class="actions">
			  	 <button class="btn btn-primary btn-block" type="submit">更新する</button>
			  </div>
			<% end %>

			<div class="col-xs-4"></div>
			<div class="col-xs-8">
			  <%= link_to "マイページに戻る＝＞", user_path(@user.id) %>
			</div>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">

     <!--サイドバー-->
	  <div class="side-bar col-xs-3">
	  	  <div class="user_info">
			 <h2>マイページ</h2>
		  </div>

		  <table class="table table-striped">
              <tr>
              	 <%= attachment_image_tag @user, :profile_image,size: '250x250',fallback: "no_image.jpg" %>
              </tr>

              <tr>
              	 <th>名前</th>
              	 <th><%= @user.name %>
              </tr>

              <tr>
              	 <th>自己紹介文</th>
              	 <th><%= @user.introduction %></th>
              </tr>
		  </table>
		  <%= link_to "編集",  edit_user_path, class: "btn btn-success btn-block" %>

		  <div class="new_field">
		  	 <h2>新規投稿</h2>
		  	 <%= link_to "新しい投稿はこちらから＝＞", new_post_path %>
		  </div>
	  </div>

      <!--ユーザが投稿した一覧-->
	  <div class="main col-xs-9">
	  	  <div class="list">
	  	     <h2>投稿一覧</h2>
	      </div>

	      <% @posts.each do |post| %>
	          <table class="table table-striped">
		          	  <tr>
		                  <td><%= attachment_image_tag post, :image, size: '100x100', fallback: "no_image.jpg" %></td>
		              	  <th class="col-xs-8">
		              	  	  タイトル　　　　　　<%= post.title %><br>
		              	 	  サブタイトル　　　　<%= post.subtitle %><br>
		              	 	  都道府県名　　　　　<%= post.region %><br>
                              市区町村・エリア名　<%= post.area %><br>
                          </th>

                          <!--いいね数＋コメント数表示-->
                          <th class="col-xs-4">
                              <% if post.favorited_by?(current_user) %>
							      <%= link_to post_favorites_path(post.id), method: :delete do %>
							      <span class="glyphicon glyphicon-heart" aria-hidden="true" style="color: red;"></span>
							      <%= post.favorites.count %>いいね<br>
							       <% end %>
						      <% else %>
							      <%= link_to post_favorites_path(post.id), method: :post do %><span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span>
							      <%= post.favorites.count %>いいね<br>
							      <% end %>
						      <% end %>
                              コメント数：<%= post.post_comments.count %><br>
                              <%= link_to "詳しくはこちら＝＞", post_path(post.id) %>
		              	  </th>
		              </tr>
              </table>
	      <% end %>
	      <!--ページネーション-->
	      <%= paginate @posts, class: "paginate" %>
	  </div>
  </div>
</div>